# Site settings
title: The Godiva Collection
client:
  name: Godiva
  link: https://www.godivachocolates.co.uk/
  shops:
    - id: asda
      name: Asda
      link: https://groceries.asda.com/search/godiva
    - id: morrisons
      name: Morrisons
      link: https://groceries.morrisons.com/search?entry=Godiva
    - id: ocado
      name: Ocado
      link: https://www.ocado.com/search?entry=Godiva
    - id: sainsburys
      name: Sainsbury's
      link: https://www.sainsburys.co.uk/webapp/wcs/stores/servlet/gb/groceries/food-cupboard/Godiva-
    - id: tesco
      name: Tesco
      link: https://www.tesco.com/groceries/en-GB/search?query=Godiva

core-se-link: https://www.secretescapes.com/current-sales
description: >
  Discover a collection of hotels for the perfect British getaway. Each has been handpicked for their uncompromising style and luxury, where country halls offer indulgent spa experiences and classic stately homes feature gorgeous contemporary flair.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/godiva" # the subpath of your site, e.g. /blog/
img:     "/uk/2020/godiva/_assets/img"
css:     "/uk/2020/godiva/_assets/css"
js:      "/uk/2020/godiva/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed